apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt-broker
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous false
    password_file /mosquitto/config/passwordfile
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    log_timestamp true
