apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-auth
  namespace: mqtt-broker
type: Opaque
stringData:
  passwordfile: |-
    lasdpc:$7$101$V1ch3V0qV8yLi0gu$zBgjDlXo7dC9FKRKKC60dt7hklVg/htyYBJDF2Wk+c3DUvHg/+EMVQ8UAyYQhshwdbB8UxyNkF51qYOlaTHaxw==